services:
  ors-app:
    build:
      context: ./
    container_name: geo-il-routing
    ports:
      - "8080:8082"
    image: geo-il-routing:latest
    volumes:
      - ./ors-docker:/home/ors
    environment:
      REBUILD_GRAPHS: False
      CONTAINER_LOG_LEVEL: INFO
      XMS: 1g # start RAM assigned to java
      XMX: 2g # max RAM assigned to java. Rule of Thumb: <PBF-size> * <profiles> * 2
      ADDITIONAL_JAVA_OPTS: ""
